 **Que)a) Create pandas DataFrame with columns 'Sales' and 'Expenses' and perform following :**

• Calculate the profit margin (Profit/Sales) for each entry.

• What is the correlation between sales and expenses in the dataset?

• Identify the entry with the highest profit margin.

• Can we predict future sales based on past sales data using a regression model?

In [49]:
import pandas as pd
import numpy as np
import scipy.stats as ss

In [50]:
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [51]:
# Create a sample DataFrame
data = ({
    'Sales': np.random.randint(100, 1000, 10),
    'Expenses': np.random.randint(50, 500, 10)})
df = pd.DataFrame(data, columns=['Expenses', 'Sales'])
print(df)


   Expenses  Sales
0       192    250
1       442    670
2       349    274
3       368    184
4       322    923
5       295    287
6       370    413
7        60    229
8        79    618
9       425    726


In [52]:
df['Profit'] = df['Sales'] - df['Expenses']
df['Profit Margin'] = df['Profit'] / df['Sales']
print(df)


   Expenses  Sales  Profit  Profit Margin
0       192    250      58       0.232000
1       442    670     228       0.340299
2       349    274     -75      -0.273723
3       368    184    -184      -1.000000
4       322    923     601       0.651138
5       295    287      -8      -0.027875
6       370    413      43       0.104116
7        60    229     169       0.737991
8        79    618     539       0.872168
9       425    726     301       0.414601


In [53]:
#correlation betweeen sales and expenses
correlation = df['Sales'].corr(df['Expenses'])
print(f"Correlation between Sales and Expenses: {correlation:.2f}")


Correlation between Sales and Expenses: 0.27


In [54]:
x=df['Sales']
y=df['Expenses']
ss.pearsonr(x,y)

PearsonRResult(statistic=0.2739527006404148, pvalue=0.4437147908601478)

In [55]:
# identify the entry with highest profit margin
highest_margin_entry = df.loc[df['Profit Margin'].idxmax()]
highest_margin_entry

Expenses          79.000000
Sales            618.000000
Profit           539.000000
Profit Margin      0.872168
Name: 8, dtype: float64

**.loc[]: This is a method for label-based indexing. It allows you to select rows and columns by their labels (such as row indices or column names).**
**df['Profit Margin']: This part extracts the ‘Profit Margin’ column from the DataFrame.**
**.idxmax(): This method returns the index (row label) corresponding to the maximum value in the specified column (in this case, ‘Profit Margin’).**

In [56]:
# to predict sales data using regression model 
# Split data into features (X) and target (y)
# Assuming 'Expenses' is your feature column and 'Sales' is the target column
X = df[['Expenses']]  # Features (2D array)
y = df['Sales']       # Target (1D array)

In [57]:
# Initialize the linear regression model
model = LinearRegression()

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
# Check the lengths of X_train and y_train it is necessary to same the length of both x_train and y_train
print(f"Length of X_train: {len(X_train)}")
print(f"Length of y_train: {len(y_train)}")

Length of X_train: 8
Length of y_train: 8


In [60]:
# Fit the model to the data
model.fit(X_train, y_train)

LinearRegression()

In [61]:
# Make predictions on the test data
y_pred = model.predict(X_test)

In [62]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared: {r2:.2f}")

Mean Squared Error: 91980.22
R-squared: -135.07


In [63]:
# Predict future sales based on new expense values
new_expenses = np.array([200, 300, 400]).reshape(-1, 1)
predicted_sales = model.predict(new_expenses)
print(f"Predicted sales for new expenses: {predicted_sales}")

Predicted sales for new expenses: [320.11447747 412.9549615  505.79544552]


C:\Users\ratne\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


b) *Write a Python program that defines a function to calculate the area of a rectangle. The function should have two parameters (length and width), with the default value of width set to 5. The program should take user input for the length and, optionally, the width. If the user doesn't provide the width, it should use the default value. Display the calculated area*

In [72]:
#define the function 
def area(length, width=5):
    return length * width

In [73]:
# Take user input for the length
length = float(input("Enter the length of the rectangle: "))

Enter the length of the rectangle:  12


In [74]:
# Take user input for the width, if provided
try:
    width = float(input("Enter the width of the rectangle (or press Enter to use the default value of 5): "))
except ValueError:
    width = 5

Enter the width of the rectangle (or press Enter to use the default value of 5):  


In [76]:
# Calculate and display the area
area_rectangle= area(length, width)
print(f"The area of the rectangle is: {area_rectangle}")

The area of the rectangle is: 60.0


*c) Write a Python program using NumPy to perform the following operations on matrices:*

Create a 3x3 matrix with fandom integer values.

Calculate the transpose of the matrix.

Find the determinant of the original matrix.

Calculate the inverse of the matrix (if the determinant is not zero).

In [87]:
# Create a 3x3 matrix with random integer values
matrix = np.random.randint(1, 10, size=(3, 3))
print("Original Matrix:")
print(matrix)

Original Matrix:
[[6 9 5]
 [9 9 3]
 [2 9 7]]


In [89]:
# Calculate the transpose of the matrix
transpose_matrix = matrix.T
print("\nTranspose of the Matrix:")
print(transpose_matrix)


Transpose of the Matrix:
[[6 9 2]
 [9 9 9]
 [5 3 7]]


In [92]:
# Find the determinant of the original matrix
determinant = np.linalg.det(matrix)
print("\nDeterminant of the Original Matrix:", determinant)


Determinant of the Original Matrix: 18.000000000000046


In [93]:
# Calculate the inverse of the matrix if the determinant is not zero
if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the Matrix:")
    print(inverse_matrix)
else:
    print("\nThe matrix is singular and does not have an inverse.")


Inverse of the Matrix:
[[ 2.         -1.         -1.        ]
 [-3.16666667  1.77777778  1.5       ]
 [ 3.5        -2.         -1.5       ]]
